import "../styles/style.scss";
import 'animate.css';

export const metadata = {
  title: "Lok Ly",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        {children}
      </body>
    </html>
  );
}
